#!/usr/bin/env node
/**
 * Regenerates index.mdx from the MDX already on disk.
 *
 * Why this exists separately from migrate-ghost.mjs: that script builds the home
 * page from the Ghost export, so it only knows about posts that came from Ghost.
 * Any post written directly as MDX from now on would never reach the home page.
 * This script reads posts/ and releases/ instead, so the home page stays correct
 * whatever the source.
 *
 *   node scripts/build-home.mjs
 *
 * Featured cards = the four newest posts. Each needs a `cover` in its
 *                  frontmatter, authored at 1200x630 so the grid lines up, and a
 *                  short `summary` (one line) that falls back to `description`.
 * Release cards  = the four newest <Update> entries across releases/*.mdx.
 */

import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
  'August', 'September', 'October', 'November', 'December'];
const ARTICLE_CARDS = 4;
const RELEASE_CARDS = 4;

const quote = (s) => `"${String(s ?? '').replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;

const longDate = (iso) => {
  const d = new Date(iso);
  return `${d.getUTCDate()} ${MONTHS[d.getUTCMonth()]} ${d.getUTCFullYear()}`;
};

const anchorFor = (label) =>
  label.toLowerCase().replace(/[^\w\s-]/g, '').trim().replace(/\s+/g, '-');

/** Minimal frontmatter reader: flat `key: value` pairs, quoted or bare. */
function frontmatter(text) {
  const m = /^---\n([\s\S]*?)\n---/.exec(text);
  if (!m) return {};
  const out = {};
  for (const line of m[1].split('\n')) {
    const kv = /^([\w:"'-]+)\s*:\s*(.*)$/.exec(line);
    if (!kv) continue;
    const key = kv[1].replace(/^["']|["']$/g, '');
    out[key] = kv[2].trim().replace(/^["']|["']$/g, '');
  }
  return out;
}

function readPosts() {
  const dir = path.join(ROOT, 'posts');
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter((f) => f.endsWith('.mdx'))
    .map((f) => {
      const fm = frontmatter(fs.readFileSync(path.join(dir, f), 'utf8'));
      return { slug: f.replace(/\.mdx$/, ''), ...fm };
    })
    .filter((p) => p.date)
    .sort((a, b) => b.date.localeCompare(a.date));
}

/** Every <Update label=".." description="..">, newest first, with its year. */
function readReleases() {
  const dir = path.join(ROOT, 'releases');
  if (!fs.existsSync(dir)) return [];
  const entries = [];
  for (const f of fs.readdirSync(dir).filter((x) => x.endsWith('.mdx'))) {
    const year = f.replace(/\.mdx$/, '');
    const text = fs.readFileSync(path.join(dir, f), 'utf8');
    const re = /<Update\s+label="([^"]+)"\s+description="([^"]+)"/g;
    let m;
    while ((m = re.exec(text))) {
      entries.push({ year, label: m[1], dateText: m[2], sort: Date.parse(m[2]) || 0 });
    }
  }
  return entries.sort((a, b) => b.sort - a.sort);
}

const posts = readPosts();
const releases = readReleases();

if (!posts.length) throw new Error('no posts found in posts/ — refusing to write an empty home page');
if (!releases.length) throw new Error('no <Update> entries found in releases/ — refusing to write an empty home page');

const featured = posts.slice(0, ARTICLE_CARDS);
const latest = releases.slice(0, RELEASE_CARDS);
const currentYear = latest[0].year;

const noCover = featured.filter((p) => !p.cover);
if (noCover.length) {
  console.warn(`  no cover: ${noCover.map((p) => p.slug).join(', ')} — those cards render short and break the grid`);
}

/**
 * Cover image, then one short line. Cards only line up when every cover shares
 * an aspect ratio, so covers are authored at 1200x630.
 */
const postCard = (p) => {
  const img = p.cover ? ` img=${quote(p.cover)}` : '';
  return [
    `  <Card title=${quote(p.title)}${img} href="/posts/${p.slug}">`,
    `    ${p.summary || p.description || p.title}`,
    '  </Card>',
  ].join('\n');
};

const releaseCard = (r) => [
  `  <Card title=${quote(r.label)} icon="rocket" href="/releases/${r.year}#${anchorFor(r.label)}">`,
  `    ${r.dateText}`,
  '  </Card>',
].join('\n');

const page = [
  '---',
  'title: "PitchPrint Blog"',
  'description: "Product news, feature announcements, and weekly release notes from the PitchPrint team."',
  'mode: "wide"',
  'hideFooterPagination: true',
  '---',
  '',
  '{/* Generated by scripts/build-home.mjs — edit the script, not this file. */}',
  '',
  '## Featured',
  '',
  '<CardGroup cols={2}>',
  featured.map(postCard).join('\n\n'),
  '</CardGroup>',
  '',
  '## Latest releases',
  '',
  `Every release ships on a Thursday. Browse the full archive on the [${currentYear} releases](/releases/${currentYear}) page.`,
  '',
  '<CardGroup cols={2}>',
  latest.map(releaseCard).join('\n\n'),
  '</CardGroup>',
  '',
  `<Card title="Subscribe to releases" icon="rss" href="/releases/${currentYear}" horizontal>`,
  '  Get every weekly release note in your feed reader, Slack, or inbox using the',
  '  RSS button at the top of the releases page.',
  '</Card>',
  '',
].join('\n');

fs.writeFileSync(path.join(ROOT, 'index.mdx'), page, 'utf8');

console.log(`index.mdx written from disk`);
console.log(`  articles: ${featured.map((p) => p.slug).join(', ')}`);
console.log(`  releases: ${latest.map((r) => r.label).join(', ')}`);
